### PR TITLE
Parse decimal numeric entities before conversion

### LINKED ISSUE #43: `&#00;` leaks NULL character
As per spec, number should be parsed before mapping against [the table](https://html.spec.whatwg.org/multipage/syntax.html#table-charref-overrides), so `&#00;` should be decoded just in the same way as `&#0;` / `&#x00;` / ..., that is, replaced with `\uFFFD`.

Currently it instead returns actual "unsafe" `\u0000` string.

### PR DESCRIPTION
**Pull request by RReverser**
Fixes #43.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Thanks!

Would you mind adding some tests for this change?

**Comment by RReverser** [comment]
@mathiasbynens Sure. Sorry, could contribute only from Github's UI at that moment and it, unfortunately, does not allow changing several files within one commit yet.

Can do somewhat later (unless you want to do that earlier :) ).

**Comment by mathiasbynens** [comment]
I’d prefer if you got the credit ;)

**Comment by RReverser** [comment]
Something very weird going on with Github. It's lagging, and apart from that - I pushed the tests, and updated commit can be seen via direct SHA-1 link https://github.com/RReverser/he/commit/3df7ef6, but branch doesn't show it and those changes don't show up in PR diff neither (even though my local Git says that remote branch is already up-to-date).

**Comment by RReverser** [comment]
Oh, it's updated now. Probably they had a DDOS or smth.

**Comment by mathiasbynens** [comment]
Thanks so much, @RReverser! :+1: :confetti_ball:

**Pull request closed without merging**
