### PR TITLE
Added &#39; character to escapeMap

### PR DESCRIPTION
**Pull request by smartapant**
`&#39;` wasn't supported

### CODE REVIEW

**Comment by mathiasbynens** [comment]
> `&#39;` wasn't supported

What do you mean? Can you provide a test case that fails with the current implementation?

**Comment by smartapant** [comment]
@mathiasbynens my bad, i've run into an issue and this fix doesn't work, so this pull request should not be merged

**Comment by mathiasbynens** [comment]
What is the issue?

**Comment by smartapant** [comment]
@mathiasbynens in string like that: &lt;div class="md"&gt;&lt;p&gt;I haven&amp;#39;t seen this posted in awhile :)&lt;/p&gt;&lt;/div&gt;

after decoding it "I haven&#39;t" is left

i was unattentive enough not to notice that &#39; was originally &amp;#39;

what can be wrong?

**Comment by smartapant** [comment]
@mathiasbynens the strings are reddit comments, maybe they were encoded wrongly, the become decoded ufter 2 decode calls in a row :)

**Pull request closed without merging**
