### PR TITLE
calling with `-v` explicitly should return success

### PR DESCRIPTION
**Pull request by bahamas10**

### CODE REVIEW

**Comment by bahamas10** [comment]
```
$ he -v; echo $?
v0.5.0
1
```

is unexpected

**Comment by mathiasbynens** [comment]
The current behavior matches the man page: https://github.com/mathiasbynens/he/blob/089b8afba8b3efe865e1c5bc38ed063103ff8a05/man/he.1#L49-L62 If you want to change it, the man page should be updated as well.

**Comment by bahamas10** [comment]
(didn't realize i was triggering so many code coverage bot triggers)

@mathiasbynens this has been updated.  the documentation now states `he` will exit with code 0 if it did what it was told to do successfully, which includes encoding/decoding data, or printing the version/usage string.

calling `he` with `-v`, `--version`, `-h` or `--help` will exit with 0, whereas calling `he` without arguments will exit with 1 (while still printing the usage message).

**Comment by mathiasbynens** [comment]
Thanks!

**Pull request closed without merging**
